sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: waimai
    username: root
    password: Kxcsxsx123456!
  alioss:
    bucket-name: sky-take-out-plus6
    endpoint: oss-cn-hangzhou.aliyuncs.com
