sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: waimai
    username: root

  alioss:
    bucket-name: sky-take-out-plus6
    endpoint: oss-cn-hangzhou.aliyuncs.com

  redis:
    host: 192.168.81.100
    port: 6379
    password: Kxcsxsx123456!
